version: '2'
services:
    rfpmate-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb rfpmate-mongodb-config
    rfpmate-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    rfpmate-mongodb-config:
        image: mongo:3.6.3
        container_name: rfpmate-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
